### PR TITLE
Add documentation about how to instantiate a selection callback

### PR DESCRIPTION
**Pull request by nlarusstone**
Hi! 

In the spirit of trying to help with documentation (https://github.com/molstar/molstar/issues/138), I wanted to put up a small PR which was confusing to me as a new user of molstar.

It took me quite a bit of time to find https://github.com/molstar/molstar/issues/412, but this eventually helped both with my question about callbacks as well as how to go from Loci -> residues.

### CODE REVIEW

**Comment by nlarusstone** [comment]
Let me know if there's anything else I can provide here

**Review by dsehnal — APPROVED** [review]
Thanks for sharing @nlarusstone and sorry for the late merge, forgot to look at it when you made this,

**Comment by dsehnal** [comment]
@nlarusstone would you please mind resolving the merge conflict?

**Comment by nlarusstone** [comment]
Resolved!

**Pull request merged**
